package drools.rules.goat;
dialect  "java"
//import com.goat.entity.Person               // 导入类
//import com.goat.examples.test.Person        // 导入类
import com.goat.examples.goat.Person        // 导入类



rule "goat1"    // 规则名，唯一
   when
        $person : Person(age<16 || age>50)     //规则的条件部分
    then
        String test = test($person.getAge().toString());
        System.out.println(test);
end


function String test(String str){

    String temp1 = "1111";
    String temp2 = "2222";
    StringBuilder sb = new StringBuilder();
    sb.append(temp1);
    sb.append(temp2);
    return sb.toString();
}
