---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 64274.
--- DateTime: 2018/11/1 21:55
---

--[[
多行注释
]]--

print("Hello,World","哥来啦！");

--定义变量
age = 100  name = "Goat" marray = false
--输出变量
print(age) print(name) print(marray)


--Lua 五种数据类型
print(age)  -- number 小数  Lua中没有整数型
print(name) -- 字符串
print(marray) -- 布尔
print(fuck) -- nil 空类型
--print(table) -- 表类型

myTable = {1,2,3,4}
print(myTable)
print(myTable[3]) -- 由此可见 在Lua中 下标从1开始  不是0

-- 获取变量类型
print(type(myTable))