---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 64274.
--- DateTime: 2018/8/28 19:54
---

local current = redis.call('GET', KEYS[1])
if current == ARGV[1]
then redis.call('SET', KEYS[1], ARGV[2])
    return true
end
return false